// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcoSnqxqN5eElZTaNZHbemqI2HJPqDorI',
    appId: '1:1047789419057:web:cdeb08537fe9a318d7f310',
    messagingSenderId: '1047789419057',
    projectId: 'fir-cossmil',
    authDomain: 'fir-cossmil.firebaseapp.com',
    storageBucket: 'fir-cossmil.firebasestorage.app',
    measurementId: 'G-96D3FTZHKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA63rk00Qg9Jf3ILBrWxy8UhFV4mF71ulY',
    appId: '1:1047789419057:android:e44b53694bd5e580d7f310',
    messagingSenderId: '1047789419057',
    projectId: 'fir-cossmil',
    storageBucket: 'fir-cossmil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD4LvMXMoP5te0j2ZnMCDZ8qyrzt4uKKo',
    appId: '1:1047789419057:ios:4f7fc7f73613ead3d7f310',
    messagingSenderId: '1047789419057',
    projectId: 'fir-cossmil',
    storageBucket: 'fir-cossmil.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD4LvMXMoP5te0j2ZnMCDZ8qyrzt4uKKo',
    appId: '1:1047789419057:ios:4f7fc7f73613ead3d7f310',
    messagingSenderId: '1047789419057',
    projectId: 'fir-cossmil',
    storageBucket: 'fir-cossmil.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcoSnqxqN5eElZTaNZHbemqI2HJPqDorI',
    appId: '1:1047789419057:web:3cb05ce270535dc7d7f310',
    messagingSenderId: '1047789419057',
    projectId: 'fir-cossmil',
    authDomain: 'fir-cossmil.firebaseapp.com',
    storageBucket: 'fir-cossmil.firebasestorage.app',
    measurementId: 'G-YLBFPQ7YYW',
  );
}
